name: solarium
description: "A modern Flutter package implementing the next generation iOS design language, bringing Apple's latest design principles to Flutter applications."
version: 0.0.0-dev.1
homepage: https://github.com/glemartret/solarium

environment:
  sdk: ^3.7.2
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
